### ISSUE TITLE
undefined macro in test case

### ISSUE THREAD

**Issue by jgm** [citation-style-language/test-suite#23]
In name_SubsequentAuthorSubstituteSingleField.txt there is a reference to a contributors-short macro, which is not defined there.
Is that intentional?
Is there a specified behavior when an undefined macro is called?  Should a processor return empty output, or should an error or warning be produced?

**Comment by adam3smith** [comment]
> Is that intentional?
No. Fix forthcoming (the undefined macros are all in the citation section which isn't used in the test at all, which is why it's presumably passing in other citeprocs)

> Is there a specified behavior when an undefined macro is called? Should a processor return empty output, or should an error or warning be produced?

I don't know; certainly not in the specs. citeproc-js returns empty, but I'm ambivalent about that: it makes style bugs less severe, but also harder to track down (e.g. a typo in a macro call which just make something not appear rather than throw an easily traceable error). 

On the style repository, we have CI tests to prevent calls to undefined macros, so at a minimum deciding to throw an error for such a call wouldn't be likely to cause much problems.

@bdarcus -- if you want to discuss whether to prescribe processor behavior on this, that should probably be a new issue. This one will close once my PR is accepted.
