### ISSUE TITLE
Question about disambiguate_AndreaEg1a.txt

### ISSUE THREAD

**Issue by jgm** [citation-style-language/test-suite#41]
I don't understand this test.  We have
```
  <citation 
         et-al-min="3"
         et-al-use-first="1"
         disambiguate-add-names="true">
```
The first citation has two cites which are identical except for the id.
Expected result, according to the test, is

```
Smith, Brown, et al. (1980); Smith, Brown, et al. (1980)
```

but why isn't it simply

```
Smith et al. (1980); Smith et al. (1980)?
```
After all et-al-use-first is 1, and "add-names" seems irrelevant here because adding names doesn't help to disambiguate the citation in this case.  It seems that the expected behavior is that we add at least one name, even if it doesn't help?  But that isn't clear from the spec.

**Comment by bdarcus** [comment]
I've assigned this to Frank and Sebastian, and copying @cormacrelf if he has any thoughts.

**Comment by jgm** [comment]
Playing with citeproc-js, I see that if you remove all but the first citation it still gives the same results.

But, then, if you ALSO remove the uncited items from the bibliography (ITEM-3 and ITEM-4), *then* you get `Smith et al. (1980; Smith et al. (1980)`.

This is unexpected, because there is no explicitly specified `given-name-disambiguation-rule`, which means that the default `by-cite` should be used. And if disambiguation is `by-cite`, if I correctly understand what that means, then the presence of uncited elements in the bibliography should be irrelevant, no?

**Comment by fbennett** [comment]
The test is in the context of a single document, with four items: 1 ,2, 3 & 4, where item 3 can be disambiguated from the others by adding one name (as Smith, Benson). Items 1, 2 & 4 remain ambiguous, but if represented by a single name (Smith), a reader flipping to the bibliography from one of those three citations would see 4 possible matches, not three. In other words, placing the second name on all citations in the set reduces the ambiguity of the set, although it does not eliminate it completely.

(I'm not sure what you mean by "uncited items.")

**Comment by cormacrelf** [comment]
Frank is exactly right. The spec says:

> [add names] ... until no more cites in the set can be disambiguated by adding names.

My approach has been to consider each cite individually with respect to the four references in the bibliography, rather than as a cite in a set of cites. That means looking at a cite, adding names one by one until there are no more names, and rolling back to the last addition that made an improvement (reduction) to the count of possible matches. Then look at another cite and do the same. It's independent but each of the four cites comes to the same result. If two cites refer to the same reference, they will end up identical.

"Uncited items" (or "uncited entries") are a term in the spec referring to references that should appear in the bibliography even if they are not cited. (They are the things the spec suggests you need to create ghost cites for.) The way they **'participate'** in disambiguation is that a cite in the document could be referring to one of them when the reader flips to the bibliography, so you have to consider that when adding names 'by-cite'. If you remove the in-document cites to items 3 & 4 and make them uncited instead, the remaining cites 1 & 2 should both be "Smith, Brown, et al. (1980)" because a reader gets a bibliography with all four references in it, and as the intuition says, the Brown narrows it down although not completely.

'by-cite' refers to using names for flip-to-the-back disambiguation just like the other methods. It means "don't do global name disambiguation before starting flip-to-the-back".

**Comment by jgm** [comment]
I get it now! thanks for your explanations.
