### ISSUE TITLE
page_Expand test sometimes updates page range delimiter, sometimes not

### ISSUE THREAD

**Issue by Jason-Abbott** [citation-style-language/test-suite#54]
The expected output for [page_Expand](https://github.com/citation-style-language/test-suite/blob/3b180057944e196aa9c12f6c6547b3eb7274b7ce/processor-tests/humans/page_Expand.txt) sometimes retains the original page range delimiter character (retaining a dash) and sometimes it replaces it with the locale standard (converting dash to en-dash).

So always keeping the existing delimiter doesn’t work and always replacing it doesn’t work. I can’t discern the expected logic.

It seems like the range character should always be updated to the standard when re-formatting a range. What am I missing?

```
Example: minimal, at 110–115
Example: prefix on first number only, at N110-5
Example: same prefix on both numbers, at N110–N115
Example: prefix on last number only, at 110-N6
Example: different prefixes on both numbers, at N110-P5
Example: leading number before prefix, at 123N110-N5
Example: multiple ranges, at 123N110-N5, 456K200-99
Example: first less than second, at 123N110-N5, 000c23-22
```

**Comment by adam3smith** [comment]
I'm pretty sure the rational here is that not all hyphens indicate ranges -- they can also, e.g., be part of an article number, in which case flipping them in clearly wrong. So the test assumes that if you have just number or you have numbers with the same prefix, that's a range, otherwise it's not. The[ relevant commit changing the test](https://github.com/citation-style-language/test-suite/commit/faded91ab21f86823f9e1ef76c65e669bcd2e73d) (which did use to be all en-dashes) also suggests that rationale.

**Comment by Jason-Abbott** [comment]
P.S. I’ll be sure to check commit history on tests before opening issues from now on. 👍

**Comment by adam3smith** [comment]
I think we'd also take PR's with comments on tests you find confusing. Ideally it shouldn't need a 7 year-old memory of a discussion on the Zotero forums to figure out the rationale for a test ;)
