### ISSUE TITLE
Missing citation date sorts as `0` but appears last?

### ISSUE THREAD

**Issue by Jason-Abbott** [citation-style-language/test-suite#70]
This will be something simple, I’m sure. [This is a little citation test](https://github.com/citation-style-language/test-suite/blob/9d60c5a1d44c300a3d4424cca9d7406105e21bc2/processor-tests/humans/date_SortEmptyDatesCitation.txt) that sorts by issued date. Three of the five citations have no issued date so they sort as if their date was `0`, as the test comment confirms: “in citations, empty dates have a value equivalent to zero.” 

And yet the expected result is
```
BookD 1999; BookB 2000; BookA; BookC; BookE.
```
which has `1999` and `2000` sorting _before_ `0`.

That makes this test the _same_ as the [bibliography variant](https://github.com/citation-style-language/test-suite/blob/9d60c5a1d44c300a3d4424cca9d7406105e21bc2/processor-tests/humans/date_SortEmptyDatesBibliography.txt), though I think the point is that citations and bibliographies should produce _different_ results.

**Comment by zepinglee** [comment]
I try to track this test in [Juris-M/citeproc-js](https://github.com/Juris-M/citeproc-js/commits/6e176ca308b1e61b9844e02edb245a2d1308aeb6/tests/std/humans/date_SortEmptyDatesCitation.txt?browsing_rename_history=true&new_path=tests/fixtures/std/date_SortEmptyDatesCitation.txt&original_branch=445be75683ba4059e1cb977022e3a15ed8c571b1) and it was first created in [Juris-M/citeproc-js@a8614a1](https://github.com/Juris-M/citeproc-js/commit/a8614a1af8bad218ccc1999a4cdbda02fcee86bc#diff-8297c3d3f18b1170ee44ba2c8ecbd5a2d4f8e45abc8ed4d5ee0bb692e3f301ff). It was then modified to treat empty year as zero in [Juris-M/citeproc-js@ae47c5f](https://github.com/Juris-M/citeproc-js/commit/ae47c5f326f1273242f9f3cd92bc0e402871eccd#diff-f81be3f667dd1c6a42e3cec8d722ab46a28209556013fd5e0253be362de87047) with those descriptions added. But in [Juris-M/citeproc-js@9af4026](https://github.com/Juris-M/citeproc-js/commit/9af40264a9c7f7089eaa4ce1f673be29388b368b#diff-f81be3f667dd1c6a42e3cec8d722ab46a28209556013fd5e0253be362de87047), it was reverted to the original behavior and the commit message says: "Fix sorting in cs:citation following agreed revision to spec, oops." The descriptions should be inaccurate since then.

**Comment by Jason-Abbott** [comment]
@zepinglee Thanks! I didn’t realize the tests were originally over there. I looked at the history in [citation-style-language/test-suite](https://github.com/citation-style-language/test-suite) and didn’t see an explanation. I’ll start checking both places before posting.

I am not noticing in [the spec](https://docs.citationstyles.org/en/stable/specification.html#sorting-variables) where this is described but I gather that both citations and bibliography items should sort missing dates last.

**Comment by Jason-Abbott** [comment]
I will follow up with a PR to change the description in that test.

**Comment by adam3smith** [comment]
FWIW, my recollection here is that this is for creating a more sensible place for n.d./in press citations, which should sort next to the most recent, not the oldest citations by default. Haven't checked specs or anything, but I think the test describes desirable behavior.

**Comment by bdarcus** [comment]
> ... my recollection here is that this is for creating a more sensible place for n.d./in press citations, which should sort next to the most recent ...

That makes sense. Can you clarify though?

By nd/in press, do you mean in press references without a projected date?

Or do you two different cases?

Nd, now that I think about it, is a different case than in-press, since the later is essentially a future date.

So while it wouldn't ever likely happen in practice, how should we sort three references from the same author, one with an issued date of "2020", and the other nd and in-press (say with an expected date?)

**Comment by bwiernik** [comment]
In press is denoted in the `status` variable so it doesn't really come into play here. Considering just the date variable, no-date and in-press look the same (just an absence of the date). 

I don't have a strong preference for whether no date come before or after. APA style sorts them before the oldest dates, but other styles sort them after the newest. If a style sorts no-date and in-press next to each other, sorting them after the newest would mean that in-press automatically gets placed correctly without having to add a macro to handle the `status` variable in sorting. So after the newest makes sense to me. 

But I think that both the citation and bibliography should sort the same. It doesn't make sense to me why they wouldn't be consistent.

**Comment by bdarcus** [comment]
> I don't have a strong preference for whether no date come before or after. APA style sorts them before the oldest dates, but other styles sort them after the newest. If a style sorts no-date and in-press next to each other, sorting them after the newest would mean that in-press automatically gets placed correctly without having to add a macro to handle the `status` variable in sorting. So after the newest makes sense to me.

Aside from clarifying the tests and/or spec, I am hoping to code this myself in my experimental project, so can I clarify a bit more?

Jane Doe has references with the following dates, and the references need to be sorted author-year.

- 2018
- 2021
- null (nd)
- null (in press)
- 2024 (in press)

You're saying APA would do this, but the first two could be switched, since they would be equivalent? In this case, a zero year for null dates would be reasonable.

1. null (nd)
2. null (in press) 
3. 2018
4. 2021
5. 2024

But that other styles might do? In this case, some random future year (say "3000") would be appropriate?

1. 2018
2. 2021
3. 2024
4. null (nd)
5. null (in press) 
 
> But I think that both the citation and bibliography should sort the same. It doesn't make sense to me why they wouldn't be consistent.

Yes, agree.

**Comment by adam3smith** [comment]
> By "nd/in press", do you mean in press references without a projected date?

> Or do you mean two different cases?

I meant two different cases, but I think my recollection was wrong, or at least what I think is desirable behavior was.

I agree with bwiernik that inconsistent behavior between citation and bibliography is a bad idea. It also seems like citeproc-js isn't actually behaving inconsistently. I'm getting the item without date sorted last in citation _and_ bibliography no matter whether I sort ascending or descending. (which goes against my recollection above of it always sorting next to the newest). 

All that said, I'd assume this is used relative rarely in styles because you'd typically sort by the date _macro_ (which would already swap in the terms for the missing date via choose/else, so the 0 never becomes relevant)  -- so contrary to what I say above, I think the most desirable behavior is probably something that's simple and consistent, in line with the current spec, and at least reasonably close to citeproc-js behavior, which turns out to be simple: 

The spec doesn't say anything about empty dates, but it does state generally

> Items with an empty sort key value are placed at the end of the sort, both for ascending and descending sorts.

which to me appears to be current citeproc-js behavior and consistent with the test, so the only thing that would need updating is the description which is confusing.

**Comment by bdarcus** [comment]
> which to me appears to be current citeproc-js behavior and consistent with the test, so the only thing that would need updating is the description which is confusing.

Does that mean it can't properly represent APA sorting?

**Comment by adam3smith** [comment]
Here's how Brenton does this in the APA style (followed by a regular date macro):

```
 <macro name="date-sort-group">
    <!-- APA sorts 1. no-date items, 2. items with dates, 3. in-press (status) items -->
    <choose>
      <if variable="issued">
        <text value="1"/>
      </if>
      <else-if variable="status">
        <text value="2"/>
      </else-if>
      <else>
        <text value="0"/>
      </else>
    </choose>
  </macro>
```

I think that's fine -- no need for us to try to pack all possible constellations into the date sort mechanism/processor

**Comment by bwiernik** [comment]
Yeah APA had some rather complicated sorting logic that is best handled by a macro.
