### ISSUE TITLE
doc: layout mismatch

### ISSUE THREAD

**Issue by gallardo** [citation-style-language/test-suite#8]
Trying to understand tests from https://github.com/Juris-M/jm-style-tests, there is a mismatch between the layout sections listed in https://github.com/citation-style-language/test-suite#fixture-layout and the sections in e.g. `apa/style_test001.txt`. This last one has:

- MODE
- KEYS
- DESCRIPTION
- RESULT
- INPUT

but no

- CSL

Furthermore, the mode `all` configured in `style_test001.txt` isn't mentioned in this doc.

**Comment by adam3smith** [comment]
https://github.com/citation-style-language/test-suite#fixture-layout is for testing CSL processors, so it tests individual outputs (i.e. citation or bibliography) and minimal CSL needs to be part of the test. Because it applies to all processors, it's part of the CSL repository.

https://github.com/Juris-M/jm-style-tests isn't fully documented and is for testing _styles_ against citeproc-js (which is why it's in the juris-m/citeproc-js repository, though the same tests could be used with other processors), so CSL is actually what's being tested. MODE `all` is just a logical extension of the logic in the processor text fixtures meaning both bibliography and citation.

**Comment by gallardo** [comment]
Thanks, I see. I guess the confusion comes from the inaccurate statement from downstream https://github.com/Juris-M/citeproc-test-runner#test-layout:

> CTR works from tests written in the idiosyncratic CSL test format, documented in the [CSL test-suite repository](https://github.com/citation-style-language/test-suite/blob/10f19d651202290d163662573f5897f768b51c4a/README.rst).

**Comment by gallardo** [comment]
:flushed: Now I read further:

> and the tests generated by CTR (see below) differ in a few respects

Sorry for the disruption
